// @ts-nocheck
// Ported verbatim from the personal Three Doors tracker (prompt builder, markdown, PDF, career helpers).
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]})}
function cap(x){x=(x||"").trim();return x?x.charAt(0).toUpperCase()+x.slice(1):""}
function dot(x){x=(x||"").trim();return !x?"":/[.!?]$/.test(x)?x:x+"."}
function lc(s){return String(s||"").toLowerCase()}
function reEsc(x){return x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function hasKw(text,k){return new RegExp("(^|[^a-z0-9])"+reEsc(k.toLowerCase())+"([^a-z0-9]|$)").test(text.toLowerCase())}
function markKw(htmlEsc,kws){if(!kws.length)return htmlEsc;var ks=kws.slice().sort(function(a,b){return b.length-a.length}).map(function(k){return reEsc(esc(k))});
  return htmlEsc.replace(new RegExp("(^|[^A-Za-z0-9])("+ks.join("|")+")(?=[^A-Za-z0-9]|$)","gi"),function(m,a,b){return a+'<mark>'+b+'</mark>'})}
function mdInline(x,kws){x=markKw(esc(x),kws||[]);return x.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\[([^\]]+)\]\(([^)]+)\)/g,"$1").replace(/(^|\s)\*(\S.*?)\*/g,"$1<em>$2</em>")}
function mdHtml(md,kws,chg){var out=[],inList=false,tb=null,C=function(t){return chg&&chg[t]?' class="chg"':''};function flushT(){if(!tb)return;var rows=tb.filter(function(r){return !/^\|?\s*:?-{2,}/.test(r)}).map(function(r){return r.replace(/^\||\|$/g,"").split("|").map(function(c){return c.trim()})});if(!rows.length){tb=null;return}out.push('<div class="tscroll"><table class="bt mdt"><thead><tr>'+rows[0].map(function(c){return "<th>"+mdInline(c,kws)+"</th>"}).join("")+'</tr></thead><tbody>'+rows.slice(1).map(function(r){return "<tr>"+r.map(function(c){return "<td>"+mdInline(c,kws)+"</td>"}).join("")+"</tr>"}).join("")+'</tbody></table></div>');tb=null}
  (md||"").split("\n").forEach(function(l){var t=l.trim(),m;
  if(/^\|.*\|$/.test(t)){if(inList){out.push("</ul>");inList=false}(tb=tb||[]).push(t);return}flushT();
  if(/^[-*] /.test(t)){if(!inList){out.push("<ul>");inList=true}out.push("<li"+C(t)+">"+mdInline(t.slice(2),kws)+"</li>");return}
  if(inList){out.push("</ul>");inList=false}
  if(!t)return;if(m=t.match(/^(#{1,3}) (.*)/))out.push("<h"+(m[1].length+1)+C(t)+">"+mdInline(m[2],kws)+"</h"+(m[1].length+1)+">");else out.push("<p"+C(t)+">"+mdInline(t,kws)+"</p>")});
  flushT();if(inList)out.push("</ul>");return out.join("")}
function nums(t){return ((t||"").match(/\d[\d,]*(?:\.\d+)?\s?(?:%|k|K|m|M|x|X|\+)?/g)||[]).map(function(n){return n.replace(/[,\s]/g,"").toLowerCase()})}
var PF_IDS=["role","field","targets","strengths","avoid","prior","years","protect","lifecycle","specialty","skills","pages","spelling","mode"];
var PF_PRESETS={
 pm:{role:"Product Manager",field:"SaaS and AI products",targets:"Product Owner, AI Product Manager, SaaS Product Manager, Product Manager – Customer Experience, Product Manager – Platform",strengths:"Product discovery and user research\nCustomer experience\nProduct strategy, roadmapping and prioritisation\nProduct analytics and experimentation\nWorkflow automation\nAI product thinking\nCross-functional delivery",avoid:"Auditor\nFinance professional\nPayments or fintech specialist\nOperations professional",prior:"finance, audit, payments",years:"Position around 2–4 years of direct product management; use the broader career as supporting evidence",protect:"",lifecycle:"user research → problem identification → data and insight → problem definition → prioritisation → strategy → roadmap → requirements → design and engineering collaboration → build → ship → measure → iterate",specialty:"AI products (LLM apps, AI agents, prototypes, evaluation, human-in-the-loop)",skills:"Product; Execution; Data & Analytics; AI & Technology",pages:"2",spelling:"Indian English",mode:"short"},
 id:{role:"Instructional Designer",field:"Corporate learning and development",targets:"Learning Experience Designer, eLearning Developer, L&D Specialist",strengths:"Training needs analysis\nWriting measurable learning outcomes\nCurriculum and course design\nAssessment design\nWorking with subject-matter experts\nUsing learner results to improve content",avoid:"Classroom teacher\nSchool administrator",prior:"school teaching",years:"Treat teaching years as transferable learning-design experience; be explicit about how much is corporate L&D",protect:"",lifecycle:"needs analysis → learning objectives → design (ADDIE or SAM) → storyboard → develop → pilot → deliver → evaluate (Kirkpatrick levels) → revise",specialty:"eLearning authoring tools such as Articulate Storyline and Rise",skills:"Learning design; Authoring tools; Evaluation & data; Stakeholder skills",pages:"1",spelling:"US English",mode:"short"},
 cs:{role:"Customer Success Manager",field:"B2B SaaS",targets:"Account Manager, Onboarding Manager, Customer Success Manager – Enterprise",strengths:"Onboarding and product adoption\nRenewals and expansion revenue\nSpotting churn risk early\nRunning business reviews with customers\nEscalating issues across product and support",avoid:"Cold-calling sales rep\nPure new-business closer",prior:"field sales",years:"State total years; separate customer-facing account ownership from new-business sales",protect:"",lifecycle:"onboarding → adoption → health monitoring → risk intervention → renewal → expansion → advocacy",specialty:"",skills:"Customer success; Commercial; Data & tools; Communication",pages:"1",spelling:"US English",mode:"short"},
 blank:{role:"",field:"",targets:"",strengths:"",avoid:"",prior:"",years:"",protect:"",lifecycle:"",specialty:"",skills:"",pages:"1",spelling:"US English",mode:"short"}};
var PF_FORM=[["The role you want",[["role","Main target role","e.g. Data Analyst","input",1],["field","Field or industry","e.g. B2B SaaS, hospital operations, retail","input"],["targets","Other titles you'd accept","Comma separated","input"]]],
 ["How you want to come across",[["strengths","Strengths to emphasise","One per line","area","The AI only uses these where your resume backs them up."],["avoid","Don't position me as","One per line. Useful if you're switching fields.","area"],["prior","Earlier fields to translate from","e.g. teaching, audit, retail sales","input"],["years","How to frame your years of experience","e.g. 8 years total, 3 in the target role","input","The prompt always makes the AI state total years honestly and separate out direct experience."],["protect","Facts the AI must never change","e.g. My 2021 role was full-time, not an internship","area","Optional. One per line."]]],
 ["What good looks like in your field",[["lifecycle","Stages of the work in this role","e.g. define question → collect data → clean → analyse → visualise → recommend → measure","area","Leave blank and the AI will work them out from the job description."],["specialty","Special area to surface, if any","e.g. AI tools, people leadership, compliance","input"],["skills","Skills section groups","e.g. Analysis; Tools; Communication","input"]]]];
function pfLines(s){return (s||"").split(/\n|;/).map(function(x){return x.trim()}).filter(Boolean)}
function buildPrompt(v,mark){
  var NS="[NOT SPECIFIED]",m=function(s){return mark?"\u0001"+s+"\u0002":s};
  var val=function(k){return v[k]&&v[k].trim()?m(v[k].trim()):NS};
  var list=function(k){var l=pfLines(v[k]);return l.length?l.map(function(x){return "- "+m(x)}).join("\n"):"- "+NS};
  var role=v.role&&v.role.trim()?m(v.role.trim()):"[TARGET ROLE]",fieldTxt=v.field&&v.field.trim()?" in "+m(v.field.trim()):"",special=v.specialty&&v.specialty.trim();
  var pages=m(v.pages==="1"?"1 page":v.pages==="2"?"2 pages":v.pages),n=9,P=function(){return "PART "+(n++)},prot=pfLines(v.protect);
  var full="1. Target role analysis\n2. JD requirements (must-have / strongly preferred / nice-to-have)\n3. Resume ↔ JD gap analysis\n4. Current resume diagnosis: what is strong, weak, missing, distracting\n5. Positioning strategy for this specific role\n6. Professional summary, final\n7. Experience, rewritten\n8. Skills, final\n9. Metrics to validate\n10. Factual / claim audit\n11. ATS keywords used (only legitimate ones from the JD)\n12. Final ATS-friendly resume, clean and ready to paste";
  var short="1. Fit verdict in 2–3 lines: how well I match and the biggest risk\n2. Gap table for must-have and strongly preferred requirements only\n3. What you changed and why, 3–6 bullets\n4. Claims I must confirm before sending\n5. Final ATS-friendly resume, clean and ready to paste";
  var bar="==============================";
  return "You are an experienced recruiter, resume strategist, ATS specialist and hiring manager for "+role+" roles"+fieldTxt+".\n\nI will give you:\n1. My current resume\n2. A target job description (JD)\n3. Optionally, my LinkedIn profile, portfolio or other career information\n\nYour job: turn my resume into a targeted, evidence-based "+role+" resume WITHOUT inventing, exaggerating or fabricating anything. Do not rewrite blindly. Diagnose it first, find my strongest evidence, find the gaps against the JD, then rewrite.\n\nAnywhere this prompt says "+NS+", infer it from my resume and the JD, and state your assumption at the top of your answer.\n\n"+
  bar+"\nPART 1 — POSITIONING\n"+bar+"\nPosition me primarily as: "+role+"\nOther target titles: "+val("targets")+"\n\nStrengths to emphasise, only where my resume supports them:\n"+list("strengths")+"\n\nDo NOT position me primarily as:\n"+list("avoid")+"\n\nEarlier experience in "+val("prior")+" can be used as evidence of scale and transferable skill. It should not become my main identity unless the JD asks for it.\n\nExperience framing: "+val("years")+"\nState my total years honestly and make clear how much of it is direct "+role+" experience. The summary must never imply more direct experience than my dates show.\n\n"+
  bar+"\nPART 2 — ANALYSE THE JD\n"+bar+"\nExtract: job title, company or product type, industry, seniority, years required, core responsibilities, required role skills, technical skills, domain knowledge, preferred qualifications, metrics mentioned, tools and frameworks, soft skills, repeated keywords, and what the hiring manager most likely wants.\nSort requirements into must-have, strongly preferred and nice-to-have. Not every keyword matters equally.\n\n"+
  bar+"\nPART 3 — GAP ANALYSIS\n"+bar+"\n| JD requirement | Evidence in my resume | Strength (Strong / Moderate / Weak / Missing) | Missing evidence | Action |\nDo not invent experience to fill a gap. Use transferable evidence only where it genuinely demonstrates the requirement. A missing requirement stays missing.\n\n"+
  bar+"\nPART 4 — STRONGEST EVIDENCE\n"+bar+"\nFind my strongest evidence of ownership, problem-solving, analysis, decisions, delivery, collaboration, and business or customer impact. Rank it internally by relevance to the JD.\n\n"+
  bar+"\nPART 5 — SUMMARY\n"+bar+"\n2–3 sentences that pass a 6-second test: who I am, what I work on, why I'm credible, the scale I've worked at, and proof of impact.\nStructure: title + domain + credibility + 2–3 proof points.\nNo generic phrases (results-driven, passionate, dynamic, highly motivated, strategic thinker, proven track record, team player, excellent communicator) unless the JD uses them.\n\n"+
  bar+"\nPART 6 — BULLETS\n"+bar+"\nFormula: what I did → how I did it → measurable result.\nWhere the facts support it: problem → insight → decision → action → result.\nAvoid \"Responsible for\", \"Worked on\", \"Helped with\", \"Participated in\", \"Assisted\" unless nothing stronger is true. Focus on what changed because of my work.\n\n"+
  bar+"\nPART 7 — NUMBERS\n"+bar+"\nQuantify every bullet where a real number exists anywhere in my material: people, customers, volume, revenue, cost, time saved, error rate, cycle time, percentage change, teams, projects.\nNEVER invent a number. If a bullet has none, keep it without one and list it under Metrics to Validate.\n\n"+
  bar+"\nPART 8 — THE FULL CYCLE OF THE WORK\n"+bar+"\nAcross the experience section as a whole (not in every bullet), show I can work across the full cycle of this role:\n"+val("lifecycle")+"\nThe reader should see judgement and outcomes, not a list of tasks.\n"+
  (special?"\n"+bar+"\n"+P()+" — "+m(special).toUpperCase()+"\n"+bar+"\nSurface my legitimate evidence of "+m(special)+". Do not claim expertise from casual tool use; use only what my experience actually shows.\n":"")+
  "\n"+bar+"\n"+P()+" — ATS\n"+bar+"\nUse the JD's terms where they truthfully match my experience. Prioritise keywords in the job title, required qualifications and responsibilities, and ones the JD repeats. Work them naturally into the summary, experience and skills. No keyword-stuffing section.\n\n"+
  bar+"\n"+P()+" — SKILLS\n"+bar+"\nA short skills section grouped under: "+val("skills")+"\nOnly skills I have evidence for.\n\n"+
  bar+"\n"+P()+" — ORDER AND CUTS\n"+bar+"\nWithin each role: the strongest relevant impact bullet first, then key decisions, then supporting execution.\nCut or condense generic duties, old or irrelevant detail, repetition, tool lists without context and unquantified claims.\nKeep experience from other fields when it proves a transferable skill. Change the emphasis, never the facts. Never hide or alter employment history.\n\n"+
  bar+"\n"+P()+" — STRUCTURE, LENGTH, STYLE\n"+bar+"\nName\nHeadline: "+role+" | 3–4 areas the JD cares most about\nContact and links\nSummary\nSkills\nExperience (Company — Role | Dates, then bullets)\nProjects (only if they strengthen the case)\nEducation\nCertifications (only if relevant)\n\nMaximum "+pages+". Use "+m(v.spelling||"US English")+" spelling.\nPlain, direct, short sentences. No corporate fluff, marketing language or buzzword stacking. Every bullet should make sense on first read.\n\n"+
  bar+"\n"+P()+" — FACT CHECK\n"+bar+"\nBefore the final resume, list: claims directly supported by my resume, metrics directly supported, claims that need my validation, and ambiguous claims. Flag, don't guess.\n"+(prot.length?"These facts must stay exactly as stated:\n"+prot.map(function(x){return "- "+m(x)}).join("\n")+"\n":"")+"\n"+
  bar+"\n"+P()+" — SELF-REVIEW\n"+bar+"\nWould a hiring manager with 10 seconds understand what kind of "+role+" I am, what I've worked on, what problems I solve, at what scale, with what results, and whether I match this JD? If not, revise before answering.\n\n"+
  bar+"\nOUTPUT, IN THIS ORDER\n"+bar+"\n"+(v.mode==="full"?full:short)+"\n\nPut no explanations inside the final resume.\n\nMOST IMPORTANT RULE\nDon't make me sound impressive. Make the evidence make me sound impressive.\nNever fabricate a number, title, responsibility, tool, customer, revenue figure or outcome.";
}
function mdLines(md){var o={};(md||"").split("\n").forEach(function(l){var t=l.trim();if(t)o[t]=1});return o}
function plain(x){return x.replace(/\*\*(.+?)\*\*/g,"$1").replace(/(^|\s)\*(\S.*?)\*/g,"$1$2").replace(/\[([^\]]+)\]\(([^)]+)\)/g,"$1 ($2)").replace(/[–—]/g,"-").replace(/[‘’]/g,"'").replace(/[“”]/g,'"')}
var TPLS={
 classic:{name:"Classic",desc:"Centred name, ruled section headings. Safe for any company.",font:"helvetica",nameSize:20,center:true,hSize:11,upper:true,rule:true,hColor:[0,0,0],body:10,lh:1.32,m:48,gap:6},
 modern:{name:"Modern",desc:"Left-aligned, navy headings, more white space. Good for startups and tech.",font:"helvetica",nameSize:22,center:false,hSize:12,upper:false,rule:false,hColor:[31,58,110],body:10,lh:1.38,m:52,gap:9},
 compact:{name:"Compact serif",desc:"Tighter spacing in a serif face. Fits a long career on fewer pages.",font:"times",nameSize:18,center:false,hSize:11,upper:true,rule:true,hColor:[0,0,0],body:10.5,lh:1.2,m:40,gap:4}};
function buildPdf(md,lib,key){var T=TPLS[key]||TPLS.classic,doc=new lib.jsPDF({unit:"pt",format:"a4"}),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),M=T.m,y=M,afterH1=false;
  function need(h){if(y+h>H-M){doc.addPage();y=M}}
  function text(t,size,style,indent,gapAfter,center,color){doc.setFont(T.font,style);doc.setFontSize(size);doc.setTextColor.apply(doc,color||[0,0,0]);var lines=doc.splitTextToSize(t,W-2*M-(indent||0)),lh=size*T.lh;
    lines.forEach(function(l){need(lh);doc.text(l,center?W/2:M+(indent||0),y+size,center?{align:"center"}:undefined);y+=lh});y+=gapAfter||0}
  md.split("\n").forEach(function(raw){var t=raw.trim(),m;if(!t){y+=T.gap/2;return}
    if(m=t.match(/^# (.*)/)){text(plain(m[1]),T.nameSize,"bold",0,3,T.center,T.center?[0,0,0]:T.hColor);afterH1=true;return}
    if(afterH1&&!/^#/.test(t)){text(plain(t),T.body-.5,"normal",0,T.gap+2,T.center,[70,70,70]);afterH1=false;return}afterH1=false;
    if(m=t.match(/^## (.*)/)){y+=T.gap;need(24);var ht=plain(m[1]);text(T.upper?ht.toUpperCase():ht,T.hSize,"bold",0,T.rule?2:3,false,T.hColor);if(T.rule){doc.setDrawColor(150);doc.setLineWidth(.6);doc.line(M,y,W-M,y);y+=6;}return}
    if(m=t.match(/^### (.*)/)){y+=T.gap/2;text(plain(m[1]),T.body+.5,"bold",0,2);return}
    if(m=t.match(/^[-*] (.*)/)){doc.setFont(T.font,"normal");doc.setFontSize(T.body);doc.setTextColor(0,0,0);need(T.body*T.lh);doc.text("•",M+4,y+T.body);text(plain(m[1]),T.body,"normal",14,1.5);return}
    text(plain(t),T.body,"normal",0,3)});
  return doc}
function durOf(t){t=lc(t).replace(/,/g,".");var y=0,hit=false,m;
  if(m=t.match(/(\d+(?:\.\d+)?)\s*(?:y|yr|yrs|year|years)\b/)){y+=+m[1];hit=true}
  if(m=t.match(/(\d+(?:\.\d+)?)\s*(?:m|mo|mos|month|months)\b/)){y+=+m[1]/12;hit=true}
  if(!hit&&(m=t.match(/((?:19|20)\d{2})\s*(?:-|to|\u2013|\u2014)\s*((?:19|20)\d{2}|present|now|today|current)/))){var b=m[2].match(/\d/)?+m[2]:new Date().getFullYear();y=Math.max(0,b-(+m[1]));hit=true}
  return hit?Math.round(y*10)/10:null}
function fmtDur(y){return y==null?"":(y===1?"1 yr":y+" yrs")}
function stepName(s,i){return (s.org||s.title||("Step "+(i+1)))}
function evOk(sk,c){var ev=lc(sk.evidence).replace(/[^a-z0-9%]+/g," ").trim();if(!ev)return false;var all=c.steps.map(function(s){return lc(s.did+" "+s.title+" "+s.org)}).join(" ").replace(/[^a-z0-9%]+/g," ");return all.indexOf(ev.slice(0,60))>=0}

export { esc, cap, dot, lc, hasKw, markKw, mdInline, mdHtml, nums, PF_IDS, PF_PRESETS, PF_FORM, pfLines, buildPrompt, mdLines, plain, TPLS, buildPdf, durOf, fmtDur, stepName, evOk };
